### ISSUE TITLE
Comparison between Sinkhorn and PD in SuperGlue.

### ISSUE THREAD

**Issue by zehongs** [HeatherJiaZG/Superglue-with-PD-Solver-#1]
Hi Zihang, Very nice work!
But I didn't find any quantitive results on your paper and this repository. Could you give some brief conclusions about matching/convergence/speed performance of Superglue-with-PD? Thanks.

**Comment by yingxin-jia** [comment]
Hello! This is Heather. I could only run with max 70 key points due to the space constraints at this time. Zihang and I are working on implementing a version incorporating sparse-sparse multiplication, which hopefully would lift the space constraints. I'd be happy to share the results with you when we finish. Thank you!

**Comment by hit2sjtu** [comment]
It seems the GPU memory consumption is way too high. Any possible fix by now?
